### PR TITLE
Fix #16: Fix MockCustomActivationProvider

### LINKED ISSUE #16: Fix MockCustomActivationProvider
`MockCustomActivationProvider` have to be registered in enrollment spring context, but this implementation depends on `enrollment-onboarding`. `PowerAuthIdentityVerificationTest` is failing.

Depends on https://github.com/wultra/enrollment-server/issues/225

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: enrollment-server/src/main/java/com/wultra/app/enrollmentserver/mock/MockCustomActivationProvider.java [hunk 1]
```diff
@@ -17,13 +17,13 @@
  * You should have received a copy of the GNU Affero General Public License
  * along with this program.  If not, see <http://www.gnu.org/licenses/>.
  */
-package com.wultra.app.onboardingserver.mock;
+package com.wultra.app.enrollmentserver.mock;
```
Comment (banterCZ) [inline enrollment-server/src/main/java/com/wultra/app/enrollmentserver/mock/MockCustomActivationProvider.java:20]: This is the main change of this PR. Other changes are just merge from the upstream.

**Review by romanstrobl — APPROVED** [review]
Looks good, thanks!

**Review by romanstrobl — APPROVED** [review]
Looks good, thanks!
